apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx/bucketrepo/charts
    clusterName: kind
    environmentGitOwner: k-von
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: openshift
    registry: ghcr.io
  environments:
  - ingress:
      domain: crc.testing
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: dev
    owner: k-von
    repository: jx3-openshift-crc
  - ingress:
      domain: ""
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: staging
  - ingress:
      domain: ""
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: production
  ingress:
    domain: apps-crc.testing
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: --token
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
