apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: k-von
    provider: https://github.com
    providerKind: github
    repositories:
    - name: kayvon-php-helloworld
    - name: php-ks-hello-world
    scheduler: in-repo
  slack:
    channel: '#jenkins-x-pipelines'
    kind: failureOrNextSuccess
    pipeline: release
